isaac-zimmerman-self-work/SG Corp/SG Corp/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SG_Corp.Models.Data;
using SG_Corp.Models.Repositories;

namespace SG_Corp.Controllers
{
    public class AdminController : Controller
    {
        public ActionResult ViewApplicants(int id)
        {
            var applicants = JobRepository.GetApplicants(id);
            return View(applicants);
        }

        public ActionResult ApplicantInfo(Applicant id)
        {
            return View(id);
        }

        [HttpGet]
        public ActionResult Jobs()
        {
            var model = JobRepository.GetAll();
            return View(model.ToList());
        }

        [HttpGet]
        public ActionResult AddJob()
        {
            return View(new Job());
        }

        [HttpPost]
        public ActionResult AddJob(Job job)
        {
            JobRepository.Add(job);
            return RedirectToAction("Jobs");
        }

        [HttpGet]
        public ActionResult JobApplications(int id)
        {
            var applicants = JobRepository.Get(id).Applicants;
            return View(applicants);
        }

        [HttpGet]
        public ActionResult EditJob(int id)
        {
            var job = JobRepository.Get(id);
            return View(job);
        }

        [HttpPost]
        public ActionResult EditJob(Job job)
        {
            JobRepository.Edit(job);
            return RedirectToAction("Jobs");
        }

        [HttpGet]
        public ActionResult DeleteJob(int id)
        {
            var job = JobRepository.Get(id);
            return View(job);
        }

        [HttpPost]
        public ActionResult DeleteJob(Job job)
        {
            JobRepository.Delete(job.JobId);
            return RedirectToAction("Jobs");
        }

    }
}

isaac-zimmerman-self-work/SG Corp/SG Corp/Controllers/ApplicationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SG_Corp.Models.Data;
using SG_Corp.Models.Repositories;
using SG_Corp.Models.ViewModels;

namespace SG_Corp.Controllers
{
    public class ApplicationController : Controller
    {
        // GET: Application
        public ActionResult Index()
        {
            var _jobs = JobRepository.GetAll();
            return View(_jobs.ToList());
        }

        public ActionResult Apply(int id)
        {
            var viewModel = new JobVM();
            viewModel.Job = JobRepository.Get(id);
            viewModel.Applicant = new Applicant();
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Apply(JobVM model)
        {
            JobRepository.AddApplicant(model.Job, model.Applicant);
            return RedirectToAction("Index");
        }

    }
}

isaac-zimmerman-self-work/SG Corp/SG Corp/Controllers/PoliciesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SG_Corp.Models.Data;
using SG_Corp.Models.Repositories;
using SG_Corp.Models.ViewModels;

namespace SG_Corp.Controllers
{
    public class PoliciesController : Controller
    {
        public ActionResult ViewCategories()
        {
            var categories = CategoryRepository.GetAll();
            return View(categories.ToList());
        }

        public ActionResult ViewPolicies(int id)
        {
            var categories = CategoryRepository.Get(id);
            return View(categories);
        }

        [HttpGet]
        public ActionResult AddPolicy(int id)
        {
            var policyVM = new PolicyVM() {Policy = new Policy(), Category = CategoryRepository.Get(id)};
            return View(policyVM);
        }

        [HttpPost]
        public ActionResult AddPolicy(PolicyVM policyVM)
        {
            CategoryRepository.AddPolicy(policyVM.Category, policyVM.Policy);
            return RedirectToAction("ViewPolicies", new {id = policyVM.Category.CategoryId});
        }

        [HttpGet]
        public ActionResult EditPolicy(Category category, int id)
        {
            var policy = CategoryRepository.GetPolicy(category, id);
            return View(policy);
        }

        [HttpPost]
        public ActionResult EditPolicy(PolicyVM policyVM)
        {
            CategoryRepository.EditPolicy(policyVM.Policy);
            return RedirectToAction("ViewPolicies", new { id = policyVM.Category.CategoryId });
        }

        [HttpGet]
        public ActionResult DeletePolicy(Category category, int id)
        {
            var policy = CategoryRepository.GetPolicy(category, id);
            return View(policy);
        }

        [HttpPost]
        public ActionResult DeletePolicy(PolicyVM policyVM)
        {
            CategoryRepository.Delete(policyVM.Policy.PolicyId);
            return RedirectToAction("ViewPolicies", new { id = policyVM.Category.CategoryId });
        }


        public ActionResult Edit()
        {
            return View();
        }

        public ActionResult EditCategories()
        {
            return View();
        }
    }
}

isaac-zimmerman-self-work/SG Corp/SG Corp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("SG Corp HR", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink("Apply", "Index", "Application", null, new { @style = "color: #fff" })
                    </li>
                    <li>
                        @Html.ActionLink("Positions", "Jobs", "Admin", null, new {@style = "color: #fff"})
                    </li>
                    <li class="dropdown">
                        <a href="#" style = "color: #fff" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Policies<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Edit Categories", "EditCategories", "Policies")</li>
                            <li>@Html.ActionLink("View Policies", "ViewCategories", "Policies")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>